services:
    app.admin.area:
        class: AppBundle\Admin\AreaAdmin
        arguments: [~, AppBundle\Entity\Area, AppBundle:AreaAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Area }
        public: true
